test(aes_ccm): fix incompatible-pointer-types warning in NIST vector test
atcab_aes_ccm_encrypt_finish() expects a uint8_t* for the tag size, but
aes_ccm_nist_vector_test() was passing the address of a size_t `taglen`,
producing:

  atca_tests_aes_ccm.c:600:62: error: passing argument 3 of
  'atcab_aes_ccm_encrypt_finish' from incompatible pointer type
  [-Wincompatible-pointer-types]

Casting the size_t* to uint8_t* would only overwrite the low byte and
leave the remaining bytes with stale content (and produce a wrong value
on big-endian). Use a local uint8_t for the API call and write the
result back into `taglen` so the subsequent
TEST_ASSERT_EQUAL_MEMORY(expected_tag, tag, taglen) sees the length
returned by the API.

Signed-off-by: Stijn Van Mol <stijnvanmol@gmail.com>