atca_iface.h: Fix function mismatches in function pointers
Newer compilers e.g. clang16 can detect signature mismatches in the
functions used as function pointers, therefore correct the function
prototypes and ensure the typedefs they use are available at the time of
use

Fixes
lib/hal/atca_hal.c:310:33: error: incompatible function pointer types       assigning to 'ATCA_STATUS (*)(ATCAIface, ATCAIfaceCfg *)' (aka 'ATCA_STATUS (*)(struct atca_iface *, ATCAIfaceCfg *)') from 'ATCA_STATUS (*)(void *, void *)' [-Wincompatible-function-      pointer-types]
                 (*hal)->halinit = cfg->atcacustom.halinit;
                                 ^ ~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Khem Raj <raj.khem@gmail.com>